# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' calculate data based on inverse distance weighted interpolation
#'
#'
#' @param i row number to analyse
#' @param inputlat latitudes of input data
#' @param inputlon longitudes of input data
#' @param inputdata input data
#' @param outputlat latitudes of output data
#' @param outputlon longitudes of output data
#' @param landmask aligned data for masking
#' @useDynLib pkgButterfly
#'
#' @keywords inverse distance weighted average
#' @export
#'
idDub <- function(i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask) {
    .Call('pkgButterfly_idDub', PACKAGE = 'pkgButterfly', i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask)
}

