# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

idDub <- function(i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask) {
    .Call('pkgButterfly_idDub', PACKAGE = 'pkgButterfly', i, inputlat, inputlon, inputdata, outputlat, outputlon, landmask)
}

